### ISSUE TITLE
Missing SampleApp.Core.csproj file.

### ISSUE THREAD

**Issue by Lonelywood** [thefex/Refit.Insane.PowerPack#1]
Hi @thefex!

The project file _SampleApp.Core.csproj_ is missing. Can you push it?

By the way, thank you for this **awesome** library.

**Comment by thefex** [comment]
Ouch, fixed :) Final release with documentation is planned on Thursday by the way.
Looks like you're from Poland... if you have time you can visit Cracow and take a look at my speech about Refit/this library - http://xamarines.com/
