### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by aflorenzan** [thefex/Refit.Insane.PowerPack#12]
I just want to start a new project and will be using the recipe Refit + Akavache + Polly for resilient networking on my Mobile App.

Found this library exploring the results of "Refit" on the Nuget Package Manager and visited the project page, read the docs and it sound really interesting to me because it already has what I need. Exploring around the repo, I realized that it has about a year without activity.

Is someone still supporting this library?

**Comment by thefex** [comment]
To be honest - everything works as expected. I use it in most of my apps.
In case something does not work you can make an issue - and just remove attributes from Refit Interfaces (as it is easily plug-in plug-out library)

I plan to move NuGet to .NetStandard and update libraries (but it works anyway with the most recent Refit)

**Comment by thefex** [comment]
Released package with NetStandard 2.0
